FROM ubuntu:18.04

# Install Node.js
RUN apt-get update
RUN apt-get install --yes curl
RUN curl --silent --location https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install --yes nodejs
RUN apt-get install --yes build-essential
RUN apt-get install --yes default-jre
RUN apt-get install --yes chromium-browser

# Binds to port 8080
EXPOSE  8080
